"""baseline

Revision ID: 57b86da17527
Revises: 
Create Date: 2026-07-27 17:12:12.139788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b86da17527'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_constraint(op.f('fk_assessment_level'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_student'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('fk_assessment_category'), 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'students', ['student_id'], ['student_id'], source_schema='sikhi_tracker', referent_schema='sikhi_tracker')
    op.create_foreign_key(None, 'assessments', 'category_levels', ['level_id'], ['id'], source_schema='sikhi_tracker', referent_schema='sikhi_tracker')
    op.create_foreign_key(None, 'assessments', 'categories', ['category_id'], ['id'], source_schema='sikhi_tracker', referent_schema='sikhi_tracker')
    op.drop_constraint(op.f('fk_level_category'), 'category_levels', type_='foreignkey')
    op.create_foreign_key(None, 'category_levels', 'categories', ['category_id'], ['id'], source_schema='sikhi_tracker', referent_schema='sikhi_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_levels', schema='sikhi_tracker', type_='foreignkey')
    op.create_foreign_key(op.f('fk_level_category'), 'category_levels', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'assessments', schema='sikhi_tracker', type_='foreignkey')
    op.drop_constraint(None, 'assessments', schema='sikhi_tracker', type_='foreignkey')
    op.drop_constraint(None, 'assessments', schema='sikhi_tracker', type_='foreignkey')
    op.create_foreign_key(op.f('fk_assessment_category'), 'assessments', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('fk_assessment_student'), 'assessments', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(op.f('fk_assessment_level'), 'assessments', 'category_levels', ['level_id'], ['id'])
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
